site_name: devenv
site_description: "Fast, Declarative, Reproducible, and Composable Developer Environments using Nix"
site_url: "https://devenv.sh"
repo_name: "cachix/devenv"
repo_url: "https://github.com/cachix/devenv"
edit_uri: "edit/main/docs"
strict: true
validation:
  omitted_files: warn
  absolute_links: info # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn # New in MkDocs 1.6
extra_css:
  - assets/top-level.css
extra_javascript:
  - javascript/highlight.min.js
  - javascript/extra.js
theme:
  name: material
  logo: assets/logo.webp
  favicon: assets/favicon.svg
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides
  palette:
    primary: white
    accent: "#FBFBFB"
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy

    # Lazily process components on the page, like code blocks.
    # Mounting all of code blocks on the reference doc page takes several
    # seconds, even on a powerful machine.
    - content.lazy

    - content.tabs.link
    - instant
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.share
    - tabs
    - toc.follow

# Exclude doc templates
exclude_docs: |
  /snippets/
  /individual-docs/**/*.md

plugins:
  search: {}
  include-markdown: {}
  awesome-nav: {}
  blog: {}
  social:
    cards_layout_options:
      background_color: "#FBFBFB"
      color: "#425C82"
  rss:
    use_git: false
    use_material_social_cards: true
    match_path: blog/posts/.*
    date_from_meta:
      as_creation: date
      as_update: date

markdown_extensions:
  - tables
  - admonition
  - pymdownx.escapeall
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.tilde
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
