[package]
name = "devenv-tasks"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
console.workspace = true
miette.workspace = true
petgraph.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
sqlx.workspace = true
blake3.workspace = true
walkdir = "2.4.0"
devenv-cache-core.workspace = true
shell-escape.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
proptest = "1.0"
tokio-test = "0.4"
